### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by wwwhdxghdgxjh** [Kalaimani02/ANN_in_Verilog#1]
Hello author, why when I run your code, there is no way to batch pass the dataset into quartus after downloading it?

**Comment by Kalaimani02** [comment]
Hi. I will attach my video link for the implementation. You can refer that for the implementation.
https://drive.google.com/file/d/1mNzdV537INSSJ7yJ6ybI-e0heRBpDlKa/view?usp=drivesdk
